# The URL for the staticman API bridge endpoint
# You will want to modify some of the values:
#  ${github-username}: the username of the account with which you publish your blog
#  ${blog-repo}: the name of your blog repository in github
#  master: this the branch out of which your blog is published, often master or gh-pages
#  ${bridge_app_name}: the name you chose in Heroku for your bridge API
#  comments: the so-called property, this defines the key in staticman.yml where the configuration is found
#
# for me, this line reads:
# staticman_url: https://${bridge_app_name}.herokuapp.com/v2/entry/${github-username}/${blog-repo}/master/comments
staticman_url: https://staticman-bridge.herokuapp.com/v2/entry/nicksherefkin/nicksherefkin.github.io/master/comments

reCaptcha:
  # the siteKey is used as-is (no encryption)
  siteKey: 6Ld5RBgaAAAAAJ39yf_WcGM3NaW07NE9ewEs0J5C
  # the secret is the encrypted blob you got back from the encrypt call
  secret: Upsz0NX+jssYpJah/LwcrQaxY+gLx+ZxVow0NCePqF/oq+0PjjxLv7PfVvHtjHQH/OeP6kRjsTlwjQWdyvuHN25/Fb0sukUhcNngyz3246+Q+LY0EobhhP2NwMrPnrUqN6rWDRMZW5y8H4NeSbZz72tP35xAotow/SeE1uEKP2mBGYnvD/uBlPp/fbCmJELzJ7DtGgfKOUrPPAzu7Mngkg2bueHTL8Otq/wWA9CXsm7Okr/6p/UZ+oJsbCufqRKPojXkb5jAI7Z8oOcTF8f+9jKX4eVoiYLGukq/rSfSPf4WQsKTpiDRH7Nz6foWv8kVQ/bCmxnHThvRSHI4Kof9zhtO1ti+RPaiTRjNnVRAp1CerVgZK5aa9UKB9QTgZHDSC09Q2RPFv7ec87zpvlg9UnIFwISsM2/JKKkQ5ZcztWo5NOv8RL9DvtYty+o9Mv45Etec1i8ySN6J+rmQrE7svbfCLcHjNXmsy7KTJmpKpNYbLvKs+c7PDiOmwBZsVqXzvrAMgWUx4ofUWJoqNG/65DSogDucjdKQaSrThozT+H5L55C0JsFMGdz1DFavrTEOouhzzjjyNS3OJl2FSCIKP0Lzw3Pne4m/ubpuFCZDS5Gq8a97/Xol7XoaVQfA/zRF0o5GIzd3My67iTH76eI3ybS4lcw1lwIgctfBn9OvDaI=